/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check application health status */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login user */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout user */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new user */
        post: operations["UsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["UsersController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update current user profile */
        patch: operations["UsersController_updateProfile"];
        trace?: never;
    };
    "/api/v1/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search available rooms */
        get: operations["RoomsController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get room details */
        get: operations["RoomsController_findById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/{id}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check room availability for date range */
        get: operations["RoomsController_checkAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user's booking history */
        get: operations["BookingsController_findByUser"];
        put?: never;
        /** Create a new booking */
        post: operations["BookingsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get booking details */
        get: operations["BookingsController_findById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cancel a booking */
        patch: operations["BookingsController_cancel"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /**
             * @description User email address
             * @example user@example.com
             */
            email: string;
            /**
             * @description User password (minimum 8 characters)
             * @example SecurePassword123!
             */
            password: string;
            /**
             * @description User full name
             * @example John Doe
             */
            name: string;
        };
        LoginDto: {
            /**
             * @description User email address
             * @example user@example.com
             */
            email: string;
            /**
             * @description User password
             * @example SecurePassword123!
             */
            password: string;
        };
        RefreshTokenDto: {
            /**
             * @description Refresh token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            refreshToken: string;
        };
        CreateUserDto: {
            /**
             * @description User email address
             * @example user@example.com
             */
            email: string;
            /**
             * @description User password (minimum 8 characters)
             * @example SecurePassword123!
             */
            password: string;
            /**
             * @description User full name
             * @example John Doe
             */
            name: string;
        };
        UpdateUserDto: {
            /**
             * @description User name
             * @example John Doe
             */
            name?: string;
            /**
             * @description User email address
             * @example john.doe@example.com
             */
            email?: string;
        };
        CreateBookingDto: {
            /**
             * @description Room ID to book
             * @example 1
             */
            roomId: number;
            /**
             * @description Check-in date (ISO date format: YYYY-MM-DD)
             * @example 2024-01-15
             */
            checkInDate: string;
            /**
             * @description Check-out date (ISO date format: YYYY-MM-DD). Must be after check-in date.
             * @example 2024-01-20
             */
            checkOutDate: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * Format: date-time
                         * @example 2024-01-01T00:00:00.000Z
                         */
                        timestamp?: string;
                        /** @example 1234.56 */
                        uptime?: number;
                    };
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description User registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        data?: {
                            user?: {
                                /** @example 1 */
                                id?: number;
                                /** @example user@example.com */
                                email?: string;
                                /** @example John Doe */
                                name?: string;
                                /** @example 2024-01-01T00:00:00.000Z */
                                createdAt?: string;
                                /** @example 2024-01-01T00:00:00.000Z */
                                updatedAt?: string;
                            };
                            tokens?: {
                                /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
                                accessToken?: string;
                                /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
                                refreshToken?: string;
                            };
                        };
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description User logged in successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        data?: {
                            user?: {
                                /** @example 1 */
                                id?: number;
                                /** @example user@example.com */
                                email?: string;
                                /** @example John Doe */
                                name?: string;
                            };
                            tokens?: {
                                accessToken?: string;
                                refreshToken?: string;
                            };
                        };
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            /** @description Token refreshed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        data?: {
                            accessToken?: string;
                            refreshToken?: string;
                        };
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User logged out successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        data?: Record<string, never>;
                        /** @example Logged out successfully */
                        message?: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            /** @description User created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        data?: {
                            /** @example 1 */
                            id?: number;
                            /** @example user@example.com */
                            email?: string;
                            /** @example John Doe */
                            name?: string;
                            /** @example 2024-01-01T00:00:00.000Z */
                            createdAt?: string;
                            /** @example 2024-01-01T00:00:00.000Z */
                            updatedAt?: string;
                        };
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User with this email already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        data?: {
                            /** @example 1 */
                            id?: number;
                            /** @example user@example.com */
                            email?: string;
                            /** @example John Doe */
                            name?: string;
                            /** @example 2024-01-01T00:00:00.000Z */
                            createdAt?: string;
                            /** @example 2024-01-01T00:00:00.000Z */
                            updatedAt?: string;
                        };
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            /** @description User profile updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        data?: {
                            /** @example 1 */
                            id?: number;
                            /** @example user@example.com */
                            email?: string;
                            /** @example John Doe */
                            name?: string;
                            /** @example 2024-01-01T00:00:00.000Z */
                            createdAt?: string;
                            /** @example 2024-01-01T00:00:00.000Z */
                            updatedAt?: string;
                        };
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email already in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoomsController_search: {
        parameters: {
            query?: {
                /** @description Items per page (default: 20, max: 100) */
                limit?: number;
                /** @description Page number (default: 1) */
                page?: number;
                /** @description Maximum price per night */
                maxPrice?: number;
                /** @description Minimum price per night */
                minPrice?: number;
                /** @description Comma-separated amenities */
                amenities?: string;
                /** @description Minimum capacity */
                capacity?: number;
                /** @description Location search term */
                location?: string;
                /** @description Check-out date (ISO format) */
                dateTo?: string;
                /** @description Check-in date (ISO format) */
                dateFrom?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rooms retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        data?: {
                            data?: {
                                /** @example 1 */
                                id?: number;
                                /** @example Cozy Studio */
                                name?: string;
                                /** @example A beautiful studio apartment */
                                description?: string;
                                /** @example New York, NY */
                                location?: string;
                                /** @example 2 */
                                capacity?: number;
                                /** @example 99.99 */
                                pricePerNight?: string;
                                /**
                                 * @example {
                                 *       "wifi": true,
                                 *       "parking": true
                                 *     }
                                 */
                                amenities?: Record<string, never>;
                                images?: string[];
                                /** @example available */
                                status?: string;
                                /**
                                 * @description Estimated total price for the date range (only included when dateFrom and dateTo are provided)
                                 * @example 499.95
                                 */
                                estimatedTotalPrice?: string;
                                /**
                                 * @description Number of nights (only included when dateFrom and dateTo are provided)
                                 * @example 5
                                 */
                                nights?: number;
                            }[];
                            pagination?: {
                                /** @example 1 */
                                page?: number;
                                /** @example 20 */
                                limit?: number;
                                /** @example 100 */
                                total?: number;
                                /** @example 5 */
                                totalPages?: number;
                            };
                        };
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoomsController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Room ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Room details retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        data?: {
                            /** @example 1 */
                            id?: number;
                            /** @example Cozy Studio */
                            name?: string;
                            description?: string;
                            location?: string;
                            capacity?: number;
                            pricePerNight?: string;
                            amenities?: Record<string, never>;
                            images?: string[];
                            status?: string;
                        };
                    };
                };
            };
            /** @description Room not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RoomsController_checkAvailability: {
        parameters: {
            query: {
                /** @description Check-out date (ISO format) */
                dateTo: string;
                /** @description Check-in date (ISO format) */
                dateFrom: string;
            };
            header?: never;
            path: {
                /** @description Room ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Availability checked successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        data?: {
                            /** @example 1 */
                            roomId?: number;
                            /** @example Cozy Studio */
                            roomName?: string;
                            /** @example 2024-01-15 */
                            dateFrom?: string;
                            /** @example 2024-01-20 */
                            dateTo?: string;
                            /** @example true */
                            available?: boolean;
                            /** @example 0 */
                            conflictingBookings?: number;
                            /**
                             * @description Total price for the date range (only included when room is available)
                             * @example 499.95
                             */
                            totalPrice?: string | null;
                            /**
                             * @description Number of nights (only included when room is available)
                             * @example 5
                             */
                            nights?: number;
                        };
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Room not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BookingsController_findByUser: {
        parameters: {
            query?: {
                limit?: number;
                page?: number;
                dateTo?: string;
                dateFrom?: string;
                status?: "pending" | "confirmed" | "cancelled" | "completed";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookings retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        data?: {
                            data?: {
                                id?: number;
                                userId?: number;
                                roomId?: number;
                                checkInDate?: string;
                                checkOutDate?: string;
                                totalPrice?: string;
                                status?: string;
                                room?: Record<string, never>;
                            }[];
                            pagination?: {
                                page?: number;
                                limit?: number;
                                total?: number;
                                totalPages?: number;
                            };
                        };
                    };
                };
            };
        };
    };
    BookingsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingDto"];
            };
        };
        responses: {
            /** @description Booking created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        data?: {
                            /** @example 1 */
                            id?: number;
                            /** @example 1 */
                            userId?: number;
                            /** @example 1 */
                            roomId?: number;
                            /** @example 2024-01-15 */
                            checkInDate?: string;
                            /** @example 2024-01-20 */
                            checkOutDate?: string;
                            /** @example 499.95 */
                            totalPrice?: string;
                            /** @example pending */
                            status?: string;
                        };
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Room not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Room not available */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BookingsController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Booking ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Booking details retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - not your booking */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Booking not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BookingsController_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Booking ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Booking cancelled successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - not your booking */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Booking not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Booking already cancelled or completed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
